Neos:
  Neos:
    fusion:
      autoInclude:
        Flownative.Anchorlinks: true
    userInterface:
      translation:
        autoInclude:
          Flownative.Anchorlinks:
            - Main
            - 'NodeTypes/*'
      requireJsPathMapping:
        Flownative.Anchorlinks/Views: 'resource://Flownative.Anchorlinks/Public/JavaScript/Inspector/Views'
    Ui:
      resources:
        javascript:
          'Flownative.Anchorlinks:AnchorView':
            resource: resource://Flownative.Anchorlinks/Public/JavaScript/AnchorView/Plugin.js
